package com.example.menubot.model;

public enum UserState {
    SELECT_LANGUAGE,
    MAIN_MENU,
    ADMIN_MENU,
    VIEWING_RESTAURANTS,
    WAITING_RESTAURANT_NAME,
    WAITING_RESTAURANT_ADDRESS,
    WAITING_RESTAURANT_PHONE,
    WAITING_RESTAURANT_DESCRIPTION,
    WAITING_CATEGORY_NAME,
    WAITING_ITEM_NAME,
    WAITING_ITEM_PRICE,
    WAITING_ITEM_DESCRIPTION,
    WAITING_ITEM_PHOTO
}